version: "3.8"
services:
    localstack-s3:
        image: localstack/localstack-full:latest
        container_name: localstack-s3
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=eu-west-2
            - DATA_DIR=/tmp/localstack/data
        ports:
            - "4566-4584:4566-4584"
            - "8080:8080"
        volumes:
            - localstack-data:/tmp/localstack
volumes:        
    localstack-data:
        name: localstack-data